// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsC_Cc77a6GKg6VfJ6EH29mpvFhAIScis',
    appId: '1:768871279458:web:2f03795324a5771dbe5a3b',
    messagingSenderId: '768871279458',
    projectId: 'waste-management-4cd0d',
    authDomain: 'waste-management-4cd0d.firebaseapp.com',
    storageBucket: 'waste-management-4cd0d.firebasestorage.app',
    measurementId: 'G-SR9CNYBH11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1_eHVtWP0hL0pRbXXOSXW7Q91keZW5JM',
    appId: '1:768871279458:android:0cd1bf738b5e98bdbe5a3b',
    messagingSenderId: '768871279458',
    projectId: 'waste-management-4cd0d',
    storageBucket: 'waste-management-4cd0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqJu3DOJO6giL6PUN_hIrgcm7N5c4Hu9E',
    appId: '1:768871279458:ios:8c94aa1b7052b91dbe5a3b',
    messagingSenderId: '768871279458',
    projectId: 'waste-management-4cd0d',
    storageBucket: 'waste-management-4cd0d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqJu3DOJO6giL6PUN_hIrgcm7N5c4Hu9E',
    appId: '1:768871279458:ios:8c94aa1b7052b91dbe5a3b',
    messagingSenderId: '768871279458',
    projectId: 'waste-management-4cd0d',
    storageBucket: 'waste-management-4cd0d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsC_Cc77a6GKg6VfJ6EH29mpvFhAIScis',
    appId: '1:768871279458:web:21ddf5d589e29a3ebe5a3b',
    messagingSenderId: '768871279458',
    projectId: 'waste-management-4cd0d',
    authDomain: 'waste-management-4cd0d.firebaseapp.com',
    storageBucket: 'waste-management-4cd0d.firebasestorage.app',
    measurementId: 'G-ZTY0QPRM3Q',
  );

}